package.loaded.ltex_extra.opts.log_level = "trace"
P(package.loaded.ltex_extra.opts.log_level)
local log = require("ltex_extra.src.log")

log.trace     ("testing")
log.debug     ("testing")
log.info      ("testing")
log.warn      ("testing")
log.error     ("testing")
log.fatal     ("testing")
log.fmt_trace ("testing")
log.fmt_debug ("testing")
log.fmt_info  ("testing")
log.fmt_warn  ("testing")
log.fmt_error ("testing")
log.fmt_fatal ("testing")

log.viminfo ("testing")
log.vimwarn ("testing")
log.vimerror("testing")
